title = 'this is the configuration file of the plugin *standing wave*'

npts = 200

[waveform]
    start = 20.0
    stop = 30.0
    rate= 200

[daqmx]
    device_ai = 'Dev3'
    channel_ai = 'ai0'
    clock_ai_terminal = 'PFI0'
    clock_rate = 20000
    trigger_ai_terminal = 'PFI1'
    trigger_enabled = false
    trigger_level = 0.5